--- #installing tomcat and java 
- hosts: webservers
  connection: ssh
  become: yes
  user: ansible

  tasks: 
   - name: install java
     yum: 
        name: java
        state: present
        
   - name: download tomcat software 
     get_url:
        url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz.sha512
        dest: /opt
   - name: unzip tomcat software
     unarchive: 
        src: apache-tomcat-8.5.81.tar.gz.sha512
        dest: /opt
        remote_src: yes

   - name: provide execcutable permission
     file:
       path: /opt/apache-tomcat-8.5.81/bin/startup.sh
       mode: 0777
    

   - name: start tomcat service
     shell: nohup ./startup.sh
     args:
       chdir: /opt/apache-tomcat-8.5.81/bin

